config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  get '/register', to: 'managers#new'
  resources :managers, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true, length: { maximum: 40 }, uniqueness: { case_sensitive: false }
  
  has_many :managers
end

app/models/manager.rb
class Manager < ApplicationRecord

  BLACKLISTED_WORDS = File.readlines(Rails.root.join('config', 'blacklist.txt')).map(&:strip)
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[a-zA-Z' ]*\z/
  VALID_USERNAME_REGEX = /\A[a-z0-9]*\z/
  
  validates :username, presence: true, length: { minimum: 3, maximum: 16 }, uniqueness: true, 
                       format: { with: VALID_USERNAME_REGEX }, 
                       exclusion: { in: BLACKLISTED_WORDS, message: "\"%{value}\" is blacklisted." }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 35 }, format: { with: VALID_NAME_REGEX }
  validates :last_name, presence: false, length: { maximum: 35 }, format: { with: VALID_NAME_REGEX }
  validates :dob, presence: true, timeliness: { before: lambda { 5.years.ago }, after: lambda { 120.years.ago }}
  validates :reg_ip, :last_ip, presence: false, length: { maximum: 45 }
  validates :online, :show_name, inclusion: { in: [true, false] }
  validates :country_id, presence: true
  
  belongs_to :country
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  def new
    @manager = Manager.new
    @countries = Country.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RedManager", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", register_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/managers/new.html.erb
<div class="container-fluid">
  <%= render 'shared/page_title', title: "Sign Up" %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@manager, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :username %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :first_name, "First Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :last_name, "Last Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :password_confirmation, "Confirm Password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :dob, "Date of Birth" %>
        </div>
        <div class="col-md-8 drop">
          <%= f.date_select :dob, class: "form-control", order: [:day, :month, :year], start_year: 1900 %>
        </div>
      </div>
      <div class="form-group required">
        <div class="control-label col-md-2">
          <%= f.label :country_id, "Country" %>
        </div>
        <div class="col-md-8 drop">
         <%= f.select :country_id, options_for_select(@countries.collect { |country|
    [country.name.titleize, country.id] }, 1), {}, { id: 'countries_select' } %>
        </div>
      </div>
        <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :show_name, "Show Name?" %>
        </div>
        <div class="col-md-1">
          <%= f.check_box :show_name, class: "form-control check" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Create Account", class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<h1>Home Page</h1>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.titleize %></h1>
<hr />